const PASE_EVENTS = Object.freeze({
  // Partida
  GAME_CREATED: "PASE_GAME_CREATED",
  GAME_STARTED: "PASE_GAME_STARTED",
  GAME_FINISHED: "PASE_GAME_FINISHED",
  GAME_CANCELLED: "PASE_GAME_CANCELLED",

  // Jugadores y tirador
  PLAYER_JOINED: "PASE_PLAYER_JOINED",
  PLAYER_LEFT: "PASE_PLAYER_LEFT",
  SHOOTER_SELECTED: "PASE_SHOOTER_SELECTED",
  SHOOTER_CONTINUED: "PASE_SHOOTER_CONTINUED",
  SHOOTER_CHANGED: "PASE_SHOOTER_CHANGED",

  // Apuestas
  INITIAL_BETS_OPENED: "PASE_INITIAL_BETS_OPENED",
  INITIAL_BET_PLACED: "PASE_INITIAL_BET_PLACED",
  BETS_CLOSED: "PASE_BETS_CLOSED",

  // Financiación del pozo
  POT_FUNDING_STARTED: "PASE_POT_FUNDING_STARTED",
  CONTRIBUTION_REQUESTED: "PASE_CONTRIBUTION_REQUESTED",
  CONTRIBUTION_ACCEPTED: "PASE_CONTRIBUTION_ACCEPTED",
  CONTRIBUTION_REJECTED: "PASE_CONTRIBUTION_REJECTED",
  PARTIAL_CONTRIBUTION_ACCEPTED:
    "PASE_PARTIAL_CONTRIBUTION_ACCEPTED",
  POT_COMPLETED: "PASE_POT_COMPLETED",

  // Dados
  DICE_ROLL_STARTED: "PASE_DICE_ROLL_STARTED",
  DICE_ROLLED: "PASE_DICE_ROLLED",
  POINT_ESTABLISHED: "PASE_POINT_ESTABLISHED",
  ROLL_CONTINUED: "PASE_ROLL_CONTINUED",

  // Resultados
  SUERTE_WON: "PASE_SUERTE_WON",
  MALA_WON: "PASE_MALA_WON",

  // Resolución económica
  SETTLEMENT_STARTED: "PASE_SETTLEMENT_STARTED",
  COMMISSION_CALCULATED: "PASE_COMMISSION_CALCULATED",
  PAYMENT_PREPARED: "PASE_PAYMENT_PREPARED",
  PAYMENT_COMPLETED: "PASE_PAYMENT_COMPLETED",
  REFUND_PREPARED: "PASE_REFUND_PREPARED",
  REFUND_COMPLETED: "PASE_REFUND_COMPLETED",

  // Estados y errores
  STATE_CHANGED: "PASE_STATE_CHANGED",
  ACTION_REJECTED: "PASE_ACTION_REJECTED",
  ERROR_OCCURRED: "PASE_ERROR_OCCURRED",
});

function isValidPaseEvent(eventName) {
  return Object.values(PASE_EVENTS).includes(eventName);
}

function getPaseEventNames() {
  return Object.values(PASE_EVENTS);
}

export {
  PASE_EVENTS,
  isValidPaseEvent,
  getPaseEventNames,
};