const PASE_STATES = Object.freeze({
  IDLE: "IDLE",
  WAITING_PLAYERS: "WAITING_PLAYERS",
  WAITING_BETS: "WAITING_BETS",
  BETS_CLOSED: "BETS_CLOSED",
  ROLLING_DICE: "ROLLING_DICE",
  RESOLVING: "RESOLVING",
  PAYING: "PAYING",
  FINISHED: "FINISHED",
  CANCELLED: "CANCELLED",
});

const PASE_STATE_FLOW = Object.freeze({
  [PASE_STATES.IDLE]: [
    PASE_STATES.WAITING_PLAYERS,
  ],

  [PASE_STATES.WAITING_PLAYERS]: [
    PASE_STATES.WAITING_BETS,
    PASE_STATES.CANCELLED,
  ],

  [PASE_STATES.WAITING_BETS]: [
    PASE_STATES.BETS_CLOSED,
    PASE_STATES.CANCELLED,
  ],

  [PASE_STATES.BETS_CLOSED]: [
    PASE_STATES.ROLLING_DICE,
  ],

  [PASE_STATES.ROLLING_DICE]: [
    PASE_STATES.RESOLVING,
  ],

  [PASE_STATES.RESOLVING]: [
    PASE_STATES.PAYING,
  ],

  [PASE_STATES.PAYING]: [
    PASE_STATES.FINISHED,
  ],

  [PASE_STATES.FINISHED]: [],

  [PASE_STATES.CANCELLED]: [],
});

export {
  PASE_STATES,
  PASE_STATE_FLOW,
};